# Generated by Django 3.1.11 on 2021-07-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210701_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
